### ISSUE TITLE
Make unionfs pluggable

### ISSUE THREAD

**Issue by ktock** [ktock/stargz-snapshotter#2]
Related to:
- [#3731@containerd](https://github.com/containerd/containerd/issues/3731#issuecomment-548115085)

Currently, we use overlayfs to merge each remote layer. So to use a different union filesystem (e.g. btrfs) we need to re-implement the snapshotter .

We can solve this issue by make union filesystem pluggable to this remote-snapshotter.

**Comment by AkihiroSuda** [comment]
How will btrfs work with this?

**Comment by ktock** [comment]
I don't have any idea yet :thinking:
@dprotaso Did you have any intention/use-case/idea about using different unionfs when you commented on [#3731@containerd](https://github.com/containerd/containerd/issues/3731#issuecomment-548115085)?

**Comment by AkihiroSuda** [comment]
that's not my comment

**Comment by ktock** [comment]
We close it until we come up with a clear vision or use-cases for this feature but feel free to reopen it if you need this kind of feature.
