### ISSUE TITLE
Do not Mount() on Prepare(), or parallelize Prepare()

### ISSUE THREAD

**Issue by AkihiroSuda** [ktock/stargz-snapshotter#37]
https://github.com/ktock/stargz-snapshotter/pull/33

`Prepare()` operations seems happening in sequential and limiting the performance.

If we skip `Mount()` on `Prepare()` and defer lazy-pull operations until actual getdents happens, probably we can see significant decrease in the startup latency.

Or maybe we should modify the unpacker so that it can unpack layers in parallel.

**Comment by ktock** [comment]
#47 addresses this issue.
